ALTER TABLE "Project"
ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "client" TEXT,
ADD COLUMN "duration" TEXT,
ADD COLUMN "overviewHtml" TEXT NOT NULL DEFAULT '',
ADD COLUMN "challengeHtml" TEXT NOT NULL DEFAULT '',
ADD COLUMN "solutionHtml" TEXT NOT NULL DEFAULT '';
